workerPoolSpecs:
  - machineSpec:
      machineType: a2-highgpu-1g
      acceleratorType: NVIDIA_TESLA_A100
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-central1-docker.pkg.dev/hostproject1-355311/pyro-repo/v58-training:latest
      args:
        - "--epochs"
        - "500"
        - "--batch-size"
        - "256"
        - "--lr"
        - "5e-5"
        - "--weight-decay"
        - "0.05"
        - "--data-bucket"
        - "gs://pyro-models-us-hostproject1-355311/processed_v58_v38_style_stride128"
        - "--checkpoint-dir"
        - "gs://pyro-models-us-hostproject1-355311/checkpoints/v58"
    diskSpec:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 1000
